#!/bin/bash

#for f in $( find . -type f -iname "*.mp4" ); do ffmpeg -i "$f" -map 0 -map -0:V -c copy  $( basename "$f" .mp4 ).stripped.mp4; done
for f in $@; do 
  ffmpeg -i "$f" -map 0 -map -0:V -c copy  $( basename "$f" .mp4 ).no-video.mp4; 
done
